### ISSUE TITLE
NewPluginTemplate_Standalone JUCE Assertion failure

### ISSUE THREAD

**Issue by robinleboe** [eyalamirmusic/JUCECmakeRepoPrototype#14]
Thanks so much for this prototype! It's a really great way to structure things. 

I'm having an issue with the NewPluginTemplate_Standalone. I'm getting 2 assertion errors when building:

JUCE Assertion failure in juce_AudioProcessor.cpp:441
JUCE Assertion failure in juce_AudioProcessor.cpp:441

Code in question:

   #if JucePlugin_Build_AU
    jassert (wrapperType == wrapperType_Undefined || param->getVersionHint() != 0);
   #endif 

NewPluginTemplate_Standalone builds fine with the assertion commented out.

**Comment by eyalamirmusic** [comment]
Thanks for reporting!
That assert comes from a new feature JUCE added on the develop branch just in the last few days (parameter versions).

Because it's so new and probably isn't stable yet, I've changed the repo to link against the master version of JUCE.

You can now pull, re-run CMake and the asserts should go away. :)

Eyal

**Comment by robinleboe** [comment]
Thanks for the quick response Eyal. All good now!
