### ISSUE TITLE
VSCODE - could not load cache

### ISSUE THREAD

**Issue by D300** [eyalamirmusic/JUCECmakeRepoPrototype#17]
Hey,

when i _build_ in the task runner of vscode i get this error

```
Executing task: CMake: build 

build task started....
opt/homebrew/Cellar/cmake/3.25.1/bin/cmake --build "/Users/dirkhandreke/Desktop/Audio Development/JUCECmakeRepoPrototypeEyal/build" --config Debug --target all -j 10 --
Error: could not load cache
build finished with error(s). 
```

i´m very new to cmake, what am i missing?

**Comment by laoguanguan** [comment]
do you solve?

**Comment by eyalamirmusic** [comment]
Hey! I'm not able to reproduce this issue here... not sure what cache could be faulty. I might need more details on what your system looks like, which OS version is it... 

Also you can try:
1. Install the latest version of Xcode (or just the command line tools).
2. Update to the latest version of CMake by calling `brew upgrade`
